def error_translate(error_code):
    error_dict = {}
    error_dict[0x00] = "Success code"
    error_dict[0x01] = "The OS object being accessed has been deleted."
    error_dict[0x02] = "Bad memory pool passed to a function."
    error_dict[0x03] = "Bad (NULL or unaligned) pointer passed to a function."
    error_dict[0x04] = "Non-zero wait requested from interrupt context."
    error_dict[0x05] = "Invalid size value passed into a function."
    error_dict[0x06] = "Invalid event group passed into a function."
    error_dict[0x07] = "Failed to set/get the event flags specified."
    error_dict[0x08] = "Invalid task option value specified for the function."
    error_dict[0x09] = "Invalid message queue passed to a function."
    error_dict[0x0A] = "The message queue being read is empty."
    error_dict[0x0B] = "The message queue being written to is full."
    error_dict[0x0C] = "Invalid semaphore pointer passed to a function."
    error_dict[0x0D] = "A semaphore get operation failed."
    error_dict[0x0E] = "Invalid thread pointer passed to a function."
    error_dict[0x0F] = "Invalid thread priority value passed to a function."
    error_dict[0x10] = "Failed to allocate memory."
    error_dict[0x11] = "Failed to delete an object because it is not idle."
    error_dict[0x12] = "Failed to resume a thread."
    error_dict[0x13] = "OS function failed because the current caller is not allowed."
    error_dict[0x14] = "Failed to suspend a thread."
    error_dict[0x15] = "Invalid timer pointer passed to a function."
    error_dict[0x16] = "Invalid (0) tick value passed to a timer function."
    error_dict[0x17] = "Failed to activate a timer."
    error_dict[0x18] = "Invalid thread pre-emption threshold value specified."
    error_dict[0x19] = "Thread suspension was cancelled."
    error_dict[0x1A] = "Wait operation was aborted."
    error_dict[0x1B] = "Failed to abort wait operation on a thread."
    error_dict[0x1C] = "Invalid Mutex pointer passed to a function."
    error_dict[0x1D] = "Failed to get a mutex."
    error_dict[0x1E] = "Failed to put a mutex because it is not currently owned."
    error_dict[0x1F] = "Error in priority inheritance."
    error_dict[0x20] = "Operation failed because relevant object is not idle or done."

    error_dict[0x40] = "One or more parameters to a function are invalid."
    error_dict[0x41] = "A null pointer has been passed in unexpectedly."
    error_dict[0x42] = "The object/module being referred to has not been started."
    error_dict[0x43] = "An object/module that is already active is being started."
    error_dict[0x44] = "Object/module referred to has not been configured."
    error_dict[0x45] = "Timeout on relevant operation."
    error_dict[0x46] = "Operation requested is not supported in current mode."
    error_dict[0x47] = "Invalid function call sequence."
    error_dict[0x48] = "Function call failed as it was aborted by another thread/isr."
    error_dict[0x49] = "DMA engine failed to completed requested operation."
    error_dict[0x4A] = "Failure due to a non-specific system error."
    error_dict[0x4B] = "Bad index value was passed in as parameter. Ex: for string descriptor."
    error_dict[0x4C] = "Bad enumeration method specified."
    error_dict[0x4D] = "Invalid configuration specified."
    error_dict[0x4E] = "Internal DMA channel creation failed."
    error_dict[0x4F] = "Internal DMA channel destroy failed."
    error_dict[0x50] = "Invalid descriptor type specified."
    error_dict[0x51] = "USB transfer was cancelled."
    error_dict[0x52] = "When a USB feature like remote wakeup is not enabled."
    error_dict[0x53] = "When a USB request / data transfer is stalled."
    error_dict[0x54] = "The block accessed has a fatal error and needs to be re-initialized."
    error_dict[0x55] = "Loss of bus arbitration, invalid bus behaviour or bus busy."
    error_dict[0x56] = "Failed to enter standby mode because one or more wakeup events are active."

    error_dict[0xFE] = "FX3 booter supports the NoReEnumeration feature that enables to have"

    return error_dict[error_code]

